add changes to lab8
cs-pub-ro/PP-laboratoare pull request #29
Opened 2022-04-14 07:55 UTC by IonutBalasescu

2022-04-14 21:02 UTC, florinrm requested changes
De fixat diacriticile, dar LGTM în rest!

2022-04-14 21:02 UTC, florinrm commented on haskell/tipuri/schelet/tipuri-skel.hs
> +  este balansat daca diferenta inaltimilor subarborilor unui nod este <= 1.
```suggestion
  este balansat dacă diferența înălțimilor subarborilor unui nod este <= 1.

```

2022-04-14 21:02 UTC, florinrm commented on haskell/tipuri/schelet/tipuri-skel.hs
> +  Aveti mai jos rezolvata si explicata o problema deosebita de
```suggestion
  Aveți mai jos rezolvată și explicată o problemă deosebită de

```

2022-04-14 21:02 UTC, florinrm commented on haskell/tipuri/schelet/tipuri-skel.hs
> +  generare de arbori infiniti. Gasiti si pasii de rezolvare in
```suggestion
  generare de arbori infiniți. Găsiți și pașii de rezolvare în

```

2022-04-14 21:02 UTC, florinrm commented on haskell/tipuri/schelet/tipuri-skel.hs
> +  inregistrarea de anul trecut aici:
```suggestion
  înregistrarea de anul trecut aici:

```

2022-04-15 09:50 UTC, mihnea-muraru requested changes
Ce am discutat pe mess

2022-04-15 09:50 UTC, mihnea-muraru commented on haskell/tipuri/README.md
> +Un asset util in implementări este alias-ul (@), care creează un sinonim pentru un tip de date în corpul unei funcții pentru simplitate.
```suggestion
Un mecanism util în implementări este alias-ul (@), care numește un pattern, astfel încât să putem accesa prin nume atât componentele unui pattern cât și pe acesta ca întreg.
```

2022-04-15 09:50 UTC, mihnea-muraru commented on haskell/tipuri/README.md
> +  | otherwise = PointC x y
De înlocuit cu funcția cealaltă, ca să se respecte tipurile

2022-04-15 11:53 UTC, florinrm approved these changes

2022-04-17 20:31 UTC, merged