Add Lab  7
cs-pub-ro/PP-laboratoare pull request #9
Opened 2021-04-11 11:40 UTC by atotputerNICA

2021-04-11 13:49 UTC, florinrm requested changes

2021-04-11 13:49 UTC, florinrm commented on haskell/tipuri/README.md
> +  - Data publicării: 11.05.2021
```suggestion
  - Data publicării: 11.04.2021
```

2021-04-11 13:49 UTC, florinrm commented on haskell/tipuri/README.md
> +  - Data ultimei modificări: 11.05.2021
```suggestion
  - Data ultimei modificări: 11.04.2021
```

2021-04-11 13:49 UTC, florinrm commented on haskell/tipuri/README.md
> +va genera o eroare de tip, fiind necesară folosirea unor funcții de conversie (de exemplu *fromIntegral*) pentru realizarea „cast”-urilor de la un tip la altul.
```suggestion
va genera o eroare de tip, fiind necesară folosirea unor funcții de conversie (de exemplu `fromIntegral`) pentru realizarea „cast”-urilor de la un tip la altul.
```

2021-04-11 13:49 UTC, florinrm commented on haskell/tipuri/README.md
> +Stabilirea statică a tipurilor este făcută cu ajutorul unui mecanism de **sinteză de tip**: la compilare sunt verificate tipurile tuturor expresiilor, compilarea terminându-se cu succes doar când ace
```suggestion
Stabilirea statică a tipurilor este făcută cu ajutorul unui mecanism de **sinteză de tip**: la compilare sunt verificate tipurile tuturor expresiilor, compilarea terminându-se cu succes doar când acestea corespund. Sinteza este efectuată pe tipuri de date oricât de complexe, astfel că, de exemplu, o expresie `expr` având tipul:
```

2021-04-11 13:49 UTC, florinrm commented on haskell/tipuri/README.md
> +Construcția `type` ne permite definirea unui **sinonim** de tip, similar cu *typedef* din C. De exemplu:
```suggestion
Construcția `type` ne permite definirea unui **sinonim** de tip, similar cu `typedef` din C. De exemplu:
```

2021-04-11 13:49 UTC, florinrm commented on haskell/tipuri/README.md
> +va fi verificată în adâncime, de la „rădăcină” (tipul listă) către „frunze” (variabila de tip *a*, tipul *Int*).
```suggestion
va fi verificată în adâncime, de la „rădăcină” (tipul listă) către „frunze” (variabila de tip `a`, tipul `Int`).
```

2021-04-11 13:49 UTC, florinrm commented on haskell/tipuri/README.md
> +Observăm distincția între *numele tipului* (denumit și *constructorde tip*), care poate fi folosit în expresii de tip (spre exemplu, `expr:: NumeTip`), și *numele constructorilor* (denumiți și *const
```suggestion
Observăm distincția între *numele tipului* (denumit și *constructor de tip*), care poate fi folosit în expresii de tip (spre exemplu, `expr:: NumeTip`), și *numele constructorilor* (denumiți și *constructori de date*), acestea fiind folosite în definiții, cum ar fi `expr = Constructor1`. De exemplu:
```

2021-04-12 08:03 UTC, atotputerNICA commented
@adelavais  @florinrm multumesc de review, am actualizat

2021-04-12 12:43 UTC, florinrm requested changes

2021-04-12 12:43 UTC, florinrm commented on haskell/tipuri/solutii/tipuri-sol.hs
> +  Pornind de la o valoare numerica x0, găsiți numărul minim de
```suggestion
  Pornind de la o valoare numerică x0, găsiți numărul minim de
```

2021-04-12 12:43 UTC, florinrm commented on haskell/tipuri/solutii/tipuri-sol.hs
> +    Putem construi un arbore binar infinit avand ca radacină un nod cu
```suggestion
    Putem construi un arbore binar infinit avand ca rădăcină un nod cu 
```

2021-04-12 12:43 UTC, florinrm commented on haskell/tipuri/solutii/tipuri-sol.hs
> +  câmp parinte, un câmp string pentru a reține funcția aplicată pe nodul curent)
```suggestion
  câmp părinte, un câmp string pentru a reține funcția aplicată pe nodul curent) 
```

2021-04-12 12:43 UTC, florinrm commented on haskell/tipuri/tipuri-skel.hs
> +  Pornind de la o valoare numerica x0, găsiți numărul minim de
```suggestion
  Pornind de la o valoare numerică x0, găsiți numărul minim de
```

2021-04-12 12:43 UTC, florinrm commented on haskell/tipuri/tipuri-skel.hs
> +    Putem construi un arbore binar infinit avand ca radacină un nod cu
```suggestion
    Putem construi un arbore binar infinit avand ca rădăcină un nod cu 
```

2021-04-12 12:43 UTC, florinrm commented on haskell/tipuri/tipuri-skel.hs
> +    Putem construi un arbore binar infinit avand ca radacină un nod cu
```suggestion
    Putem construi un arbore binar infinit avand ca rădăcină un nod cu 
```

2021-04-12 12:43 UTC, florinrm commented on haskell/tipuri/tipuri-skel.hs
> +  câmp parinte, un câmp string pentru a reține funcția aplicată pe nodul curent)
```suggestion
  câmp părinte, un câmp string pentru a reține funcția aplicată pe nodul curent) 
```

2021-04-12 15:49 UTC, florinrm approved these changes

2021-04-12 15:52 UTC, merged